web/router.ex
defmodule Dnaritag.Router do
  @moduledoc false

  use Dnaritag.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", Dnaritag do
    pipe_through [:browser]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  scope "/", Dnaritag do
    pipe_through :browser

    get "/privacy", PrivacyController, :index
    get "/term", TermController, :index
    get "/", PageController, :index

    resources "/batches", BatchController, only: [:new, :create]
    resources "/certificates", CertificateController
    resources "/collections", CollectionController
    resources "/items", ItemController
    resources "/providers", ProviderController
    resources "/providers/:provider_id/validations",
      ValidationController, only: [:show, :index]
    resources "/registrations", RegistrationController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/validations", ValidationController, only: [:show, :index]
  end

  scope "/api", Dnaritag do
    pipe_through :api
    resources "/providers/:name", ProviderController, only: [:index]
  end
end

web/controllers/collection_controller.ex
defmodule Dnaritag.CollectionController do
  @moduledoc """
  Collection Controller
  """

  use Dnaritag.Web, :controller
  import Dnaritag.Certification
  import Dnaritag.Login

  def index(conn, _params) do
    user = check_user(conn)
    certificates = get_certificates(user.id)
    render conn, "index.html", certificates: certificates
  end
end

web/views/collection_view.ex
defmodule Dnaritag.CollectionView do
  use Dnaritag.Web, :view
end

web/templates/collection/add_button.html.eex
<div class="row mt-4 justify-content-center">
  <div class="col-12 col-md-8 col-lg-4">
    <div class="form-group">
      <%= link "Agrega una nueva experiencia a tu Colección", to: "/providers/", class: "btn btn-block btn-primary" %>
    </div>
  </div>
</div>

web/templates/collection/empty_collection.html.eex
<div class="row justify-content-center">
  <div class="col-12">
    <h3>Todavía no has agregado nada a tu colección</h3>
    <h4>Experimenta, disfruta, colecciona</h4>
  </div>
</div>

web/templates/collection/full_collection.html.eex
<div class="card-group">
  <%= for cert <- @certificates do %>
    <div class="card" style="max-width:300px;">
      <img class="card-img-top" style="width:100%"
        src='<%= "/images/items/#{cert.item.id}" %>.jpg' alt="item">
      <div class="card-block">
        <h4 class="card-title"><%= cert.item.provider.name %></h4>
        <p class="card-text">
          <small class="text-muted">Desde: <%= cert.updated_at %></small>
        </p>
      </div>
    </div>
  <% end %>
</div>

web/templates/collection/index.html.eex
<%= render Dnaritag.PageView, "header.html", conn: @conn %>

<div class="container">
  <%= render "add_button.html" %>
  <div class="row">
    <div class="col-12">
      <%= if Enum.empty?(@certificates) do %>
        <%= render "empty_collection.html" %>
      <% else %>
        <%= render "full_collection.html", certificates: @certificates %>
      <% end %>
    </div>
  </div>
</div>

web/templates/collection/item.html.eex
<style>
 .mdl-card__media {
   margin: 0;
  }
</style>

<li class="mdl-color--grey-100">
<%= link to: certificate_path(@conn, :show, @certificate.id), class: "dna-item-link" do %>
  <div class="mdl-card">
    <figure class="mdl-card__media mdl-color--grey-100">
      <img class="dna-collection-item" alt="items" src="/images/items/<%= @certificate.item.id %>.jpg"/>
    </figure>
    <div class="mdl-card__title mdl-color--grey-200">
      <h5 class="mdl-card__subtitle-text"><%= @certificate.item.provider.name %></h5>
    </div>
    <div class="mdl-card__supporting-text">
      <p>
        <strong><%= @certificate.item.name %></strong>
      </p>
      <p>
        Fecha de registro:
        <br/>
        <%= @certificate.updated_at %>
      </p>
    </div>
  </div>
<% end %>
</li>