web/router.ex
defmodule Dnaritag.Router do
  @moduledoc false

  use Dnaritag.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", Dnaritag do
    pipe_through [:browser]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  scope "/", Dnaritag do
    pipe_through :browser

    get "/privacy", PrivacyController, :index
    get "/term", TermController, :index
    get "/", PageController, :index

    resources "/batches", BatchController, only: [:new, :create]
    resources "/certificates", CertificateController
    resources "/collections", CollectionController
    resources "/items", ItemController
    resources "/providers", ProviderController
    resources "/providers/:provider_id/validations",
      ValidationController, only: [:show, :index]
    resources "/registrations", RegistrationController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/validations", ValidationController, only: [:show, :index]
  end

  scope "/api", Dnaritag do
    pipe_through :api
    resources "/providers/:name", ProviderController, only: [:index]
  end
end

web/models/certificate.ex
defmodule Dnaritag.Certificate do
  use Dnaritag.Web, :model

  schema "certificates" do
    field :status, :string
    field :dnaritag, :string
    belongs_to :batch, Dnaritag.Batch
    belongs_to :item, Dnaritag.Item
    belongs_to :user, Dnaritag.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:status, :dnaritag, :batch_id, :item_id])
    |> validate_required([:status, :dnaritag, :batch_id, :item_id])
  end
end

web/controllers/certificate_controller.ex
defmodule Dnaritag.CertificateController do
  @moduledoc """
  Certificate Controller
  """

  use Dnaritag.Web, :controller
  import Dnaritag.Login

  alias Dnaritag.Certificate

  def index(conn, _params) do
    certificates = Repo.all(Certificate)
    render(conn, "index.html", certificates: certificates)
  end

  def new(conn, _params) do
    changeset = Certificate.changeset(%Certificate{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"certificate" => certificate_params}) do
    changeset = Certificate.changeset(%Certificate{}, certificate_params)

    case Repo.insert(changeset) do
      {:ok, _certificate} ->
        conn
        |> put_flash(:info, "Certificate created successfully.")
        |> redirect(to: certificate_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    check_user(conn)
    certificate = Certificate |> Repo.get!(id) |> Repo.preload(item: :provider)
    render(conn, "show.html", certificate: certificate,
      item: certificate.item, provider: certificate.item.provider)
  end

  def edit(conn, %{"id" => id}) do
    certificate = Repo.get!(Certificate, id)
    changeset = Certificate.changeset(certificate)
    render(conn, "edit.html", certificate: certificate, changeset: changeset)
  end

  def update(conn, %{"id" => id, "certificate" => certificate_params}) do
    certificate = Repo.get!(Certificate, id)
    changeset = Certificate.changeset(certificate, certificate_params)

    case Repo.update(changeset) do
      {:ok, certificate} ->
        conn
        |> put_flash(:info, "Certificate updated successfully.")
        |> redirect(to: certificate_path(conn, :show, certificate))
      {:error, changeset} ->
        render(conn, "edit.html", certificate:
          certificate, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    certificate = Repo.get!(Certificate, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(certificate)

    conn
    |> put_flash(:info, "Certificate deleted successfully.")
    |> redirect(to: certificate_path(conn, :index))
  end
end

web/views/certificate_view.ex
defmodule Dnaritag.CertificateView do
  use Dnaritag.Web, :view

  def get_certificate_state(certificate) do
    cond do
      certificate.status == "NEW" -> :new
      certificate.status == "OWNED" -> :owned
      certificate.status == "INVALID" -> :invalid
    end
  end

  def markdown(text) do
    text
    |> Earmark.to_html
    |> raw
  end
end

web/templates/certificate/certificate_card.html.eex
<div class="card">
  <h3 class="card-header"><%= @provider.name %></h3>
  <img class="card-img-top" style="width:100%" alt="item" src="/images/items/<%= @item.id %>.jpg"/>
  <div class="card-block">
    <h4 class="card-title"><%= @item.name %></h4>
    <hr class="m-1"/>
    <div class="card-text dna-item-description">
      <%= markdown(@item.description) %>
    </div>
    <div>
      <hr class="m-1"/>
      <%= if get_certificate_state(@certificate) == :owned do %>
        <div>
          <span>Esta pieza ya pertenece a una colección privada</span>
        </div>
      <%= end %>
      <%= if get_certificate_state(@certificate) == :new do %>
        <div>
        <span>Si eres el afortunado dueño de esta pieza, </span>
          <%= link "Regístrala en tu Colección", to: registration_path(@conn, :show, @certificate) %>
      </div>
     <%= end %>
    </div>
  </div>
</div>

web/templates/certificate/edit.html.eex
<h2>Edit certificate</h2>

<%= render "form.html", changeset: @changeset,
                        action: certificate_path(@conn, :update, @certificate) %>

<%= link "Back", to: certificate_path(@conn, :index) %>

web/templates/certificate/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="mdl-grid mdl-color--white">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= label f, :batch_id, class: "mdl-textfield__label" %>
      <%= text_input f, :batch_id, class: "mdl-textfield__input" %>
      <%= error_tag f, :batch_id %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= label f, :item_id, class: "mdl-textfield__label" %>
      <%= text_input f, :item_id, class: "mdl-textfield__input" %>
      <%= error_tag f, :item_id %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= label f, :status, class: "mdl-textfield__label" %>
      <%= text_input f, :status, class: "mdl-textfield__input" %>
      <%= error_tag f, :status %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= label f, :dnaritag, class: "mdl-textfield__label" %>
      <%= text_input f, :dnaritag, class: "mdl-textfield__input" %>
      <%= error_tag f, :dnaritag %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= submit "Submit", class: "mdl-button" %>
    </div>
  </div>
<% end %>

web/templates/certificate/index.html.eex
<div class="mdl-card__title mdl-color--grey-200">
  <span class="dna-center">
    <h2 class="mdl-card__title-text">Listing Certificates</h2>
  </span>
</div>

<div class="dna-card__content mdl-card__supporting-text">
  <table class="dna-table mdl-data-table mdl-js-data-table">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">Batch</th>
        <th class="mdl-data-table__cell--non-numeric">Item</th>
        <th class="mdl-data-table__cell--non-numeric">User</th>
        <th class="mdl-data-table__cell--non-numeric">Status</th>
        <th class="mdl-data-table__cell--non-numeric">Dnaritag</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for certificate <- @certificates do %>
        <tr>
          <td class="mdl-data-table__cell--non-numeric"><%= certificate.batch_id %></td>
          <td class="mdl-data-table__cell--non-numeric"><%= certificate.item_id %></td>
          <td class="mdl-data-table__cell--non-numeric"><%= certificate.user_id %></td>
          <td class="mdl-data-table__cell--non-numeric"><%= certificate.status %></td>
          <td class="mdl-data-table__cell--non-numeric"><%= certificate.dnaritag %></td>

          <td class="text-right">
            <%= link "Show", to: certificate_path(@conn, :show, certificate), class: "btn btn-default btn-xs" %>
            <%= link "Edit", to: certificate_path(@conn, :edit, certificate), class: "btn btn-default btn-xs" %>
            <%= link "Delete", to: certificate_path(@conn, :delete, certificate), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="mdl-color--grey-100 mdl-card__actions mdl-card--border">
  <%= link "New certificate", to: certificate_path(@conn, :new), class: "mdl-button" %>
</div>

web/templates/certificate/new.html.eex
<h2>New certificate</h2>

<%= render "form.html", changeset: @changeset,
                        action: certificate_path(@conn, :create) %>

<%= link "Back", to: certificate_path(@conn, :index) %>

web/templates/certificate/show.html.eex
<link rel="stylesheet" href='<%= "/images/providers/#{@provider.id}/style.css" %>'>
<div class="dna-vertical-container container">
  <div class="dna-vertical-container row align-items-center">
    <div class="hidden-sm-down col-md-6 text-center">
      <img alt="item" src='<%= "/images/providers/#{@provider.id}/logo.svg" %>' />
    </div>
    <div class="col-12 col-md-6">
      <%= render "certificate_card.html", conn: @conn, provider: @provider, item: @item, certificate: @certificate %>
    </div>
  </div>
</div>